### Тема "Вычисления с помощью Numpy"

Задание 1

In [8]:
import sys

In [2]:
!conda install --yes --prefix {sys.prefix} numpy

Solving environment: ...working... done

# All requested packages already installed.

Retrieving notices: ...working... done


In [3]:
import numpy as np

In [4]:
print (np.__version__)

1.21.5


In [5]:
a = np.array([[1,6],
              [2,8],
              [3,11],
              [3,10],
              [1,7]])

In [6]:
print(a)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [7]:
print(a.ndim)
print(a.shape)

2
(5, 2)


In [9]:
mean_a = a.mean(axis=0)

In [10]:
print(mean_a)

[2.  8.4]


Задание 2

In [11]:
print(a)
print(mean_a)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]
[2.  8.4]


In [16]:
a_centered = a - mean_a

In [17]:
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


Задание 3

In [18]:
a_centered_sp = a_centered.T[0] @ a_centered.T[1]
print(a_centered_sp)

8.0


In [19]:
a_centered_sp / (a_centered.shape[0] - 1)

2.0

### Тема "Работа с данными в Pandas"

Задание 1

In [20]:
import pandas as pd

In [21]:
print (pd.__version__)

1.4.4


In [22]:
a = {
    "author_id": [1, 2, 3],
    "author_name": ['Тургенев', 'Чехов', 'Островский']
}
authors = pd.DataFrame(a)
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [24]:
b = {
    "author_id": [1, 1, 1, 2, 2, 3, 3],
    "book_title": ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза',
                   'Таланты и поклонники'],
    "price": [450, 300, 350, 500, 450, 370, 290]
}
book = pd.DataFrame(b)
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

Задание 2

In [26]:
authors_price = pd.merge(authors, book, on='author_id', how='inner')

In [27]:
print(authors_price)

   author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290


In [28]:
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

Задание 3

In [30]:
top5 = authors_price.nlargest(5, "price")
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

Задание 4

In [36]:
authors_stat = authors_price.groupby("author_name").agg({"price": ["min", "max", "mean"]})
authors_stat

price                 
              min  max        mean
author_name                       
Островский    290  370  330.000000
Тургенев      300  450  366.666667
Чехов         450  500  475.000000